# SPDX-License-Identifier: GPL-2.0
# OPLUS Performance Optimization Drivers

obj-y += cpufreq_bouncing/
obj-y += foreground_io_opt/
obj-y += input_boost/
obj-y += iomonitor/
obj-y += lowmem_dbg/
obj-y += memory_isolate/
obj-y += multi_kswapd/
obj-y += sched_assist/
obj-y += special_opt/
obj-y += task_cpustats/
obj-y += tpd/
obj-y += tpp/
obj-y += uifirst/
obj-y += uxio_first/
obj-y += zwb_handle/
obj-y += healthinfo/
obj-y += im/
obj-y += memleak_detect/
obj-y += oplus_mm/
obj-y += oplus_nandswap/
obj-y += process_reclaim/

# Optional modules
obj-$(CONFIG_OPLUS_GLOOM) += gloom/
obj-$(CONFIG_OPLUS_GLOOM_NEW) += gloom_new/
obj-$(CONFIG_OPLUS_ION_BOOST_POOL) += ion_boost_pool/
obj-$(CONFIG_OPLUS_MULTI_FREEAREA) += multi_freearea/
obj-$(CONFIG_OPLUS_VM_ANTI_FRAGMENT) += vm_anti_fragment/
